spring:
    application:
        name: ReceiptSharingBackend

#    datasource:
#        url: jdbc:postgresql://localhost:5433/receipt_sharing
#        username: postgres
#        password: postgres
#        driver-class-name: org.postgresql.Driver
    datasource:
        url: jdbc:h2:file:./data/demo
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
logging:
    level:
        org:
            springframework:
                security=DEBUG: